name: wolofbat
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  dio: ^4.0.6
  mime: ^1.0.2
  path_provider: ^2.0.11
  intl: ^0.17.0
  crypton: ^2.0.5
  uuid: ^3.0.6
  firebase_core: ^1.19.1
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  one_context: ^2.1.0
  shimmer: ^2.0.0
  carousel_slider: ^4.1.1
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    
  assets:
    - assets/images/
    - assets/svgs/ 
